### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by mmartinello** [psy0rz/zarafa-spamd#1]
After some minutes I run kopano-dspam I get the following error:

```
2019-02-13 18:35:45,757 - dspam - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kopano/log.py", line 103, in log_exc
    try: yield
  File "/opt/kopano-dspam/kopano_dspam/__init__.py", line 123, in update
    retrained = ( db_get(self.retrained_db, spam_user+"-"+spam_id) == "1" )
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

So it seems to not work.

Could you help me please?

**Comment by psy0rz** [comment]
Which version of kopano are you using?

Are you using the latest kopano-dspam script?

**Comment by mmartinello** [comment]
> Which version of kopano are you using?

I'm using kopano-server 8.7.0 on Debian 9:

```
root@groupware:/# dpkg -l |grep kopano-server
ii  kopano-server                              8.7.0.0-0+1.1                              amd64        Server component for Kopano Core
```

> Are you using the latest kopano-dspam script?

Yes, commit 2bd4ece.

Thanks!

**Comment by mmartinello** [comment]
@psy0rz, any news about? Thanks!

**Comment by psy0rz** [comment]
sorry, didnt have time yet. I have to upgrade to the new kopano version before i can test this.
